# Stage 1: Build the Go application
FROM golang:alpine AS build

WORKDIR /app

COPY . .

RUN go mod download
RUN go build -o server .

# Stage 2: Create a minimal image
FROM alpine:latest

WORKDIR /app

COPY --from=build /app .

EXPOSE 4000

ENTRYPOINT [ "./server" ]