# Stage 1: Build the Go application
FROM golang:alpine AS build

WORKDIR /app

COPY . .

RUN go mod download
RUN go build -o app .

# Stage 2: Create a minimal image
FROM alpine:latest

WORKDIR /app

COPY --from=build /app .

EXPOSE 4000

ENTRYPOINT [ "./app", "server", "-p", "4000" ]