// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"database/sql"
	"forum/internal/handler/post"
	"forum/internal/repository"
	"forum/internal/service"
)

// Injectors from wire.go:

func InitializeListPostHandler(db *sql.DB) *post.ListPostHandler {
	postRepository := repository.NewPostRepository(db)
	postService := service.NewPostService(postRepository)
	listPostHandler := post.NewListPostHandler(postService)
	return listPostHandler
}

func InitializeGetPostHandler(db *sql.DB) *post.GetPostHandler {
	postRepository := repository.NewPostRepository(db)
	postService := service.NewPostService(postRepository)
	getPostHandler := post.NewGetPostHandler(postService)
	return getPostHandler
}

func InitializeCreatePostHandler(db *sql.DB) *post.CreatePostHandler {
	postRepository := repository.NewPostRepository(db)
	postService := service.NewPostService(postRepository)
	createPostHandler := post.NewCreatePostHandler(postService)
	return createPostHandler
}

func InitializeDeletePostHandler(db *sql.DB) *post.DeletePostHandler {
	postRepository := repository.NewPostRepository(db)
	postService := service.NewPostService(postRepository)
	deletePostHandler := post.NewDeletePostHandler(postService)
	return deletePostHandler
}
